### ISSUE TITLE
Roboclaw _node process has died.

### ISSUE THREAD

**Issue by raess1** [sonyccd/roboclaw_ros#13]
HI,
I am trying out the roboclaw with ros and i have sucessfully made it work with teleop_twist_keyboard and joy_teleop. The problem is that the Roboclaw_node dies after a while when i have the button "pressed in" or the joystick pressed in.

I get the following error:

process[rosout-1]: started with pid [14545]
started core service [/rosout]
process[roboclaw_node-2]: started with pid [14562]
process[diagnostic_aggregator-3]: started with pid [14563]
Traceback (most recent call last):
  File "/home/nvidia/rfbot/src/roboclaw_ros/roboclaw_node/nodes/roboclaw_node.py", line 305, in <module>
    node.run()
  File "/home/nvidia/rfbot/src/roboclaw_ros/roboclaw_node/nodes/roboclaw_node.py", line 232, in run
    rospy.logdebug(" Encoders %d %d" % (enc1, enc2))
TypeError: %d format: a number is required, not NoneType
[roboclaw_node-2] process has died [pid 14562, exit code 1, cmd /home/nvidia/rfbot/src/roboclaw_ros/roboclaw_node/nodes/roboclaw_node.py __name:=roboclaw_node __log:=/home/nvidia/.ros/log/ae2a0626-c880-11e7-8a40-00044b8cfad9/roboclaw_node-2.log].
log file: /home/nvidia/.ros/log/ae2a0626-c880-11e7-8a40-00044b8cfad9/roboclaw_node-2*.log

any suggestions how to fix this?

**Comment by vishu2287** [comment]
@raess1 . I am facing same issue. could you fix it? if so please help me to overcome this issue

**Comment by raess1** [comment]
I changed to this instead https://github.com/doisyg/roboclaw_ros

**Comment by vishu2287** [comment]
hi @raess1 .
Thank you for your response. i have cloned it and compiled. 
there is no error which mentioned about. though there is **no response in motor movements**. I have also changed odometry ticks and checked under /odom topic. i moved robot manually for meter and found the values are correct. 
apart from changes in odometry ticks, is there any thing to do?
I have tested in windows ionstudio. it is working well.

thank you
vishu

**Comment by Rafcin** [comment]
This Doisyg node you posted also fails to work. It has trouble reading data.
