### ISSUE TITLE
Issue launching Roboclaw 

### ISSUE THREAD

**Issue by DariusStu** [sonyccd/roboclaw_ros#24]
I'm having issues when trying to run the robolcaw node. I'm using this roboclaw_ros package and haven't changed any of the source code. I get the follwing error: 

[FATAL] [1592845100.478977]: Could not connect to Roboclaw
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py", line 568, in signal_shutdown
    h()
  File "/home/nano/catkin_ws/src/roboclaw_ros/roboclaw_node/nodes/roboclaw_pyscript.py", line 318, in shutdown
    roboclaw.ForwardM1(self.address, 0)
  File "/home/nano/catkin_ws/src/roboclaw_ros/roboclaw_node/src/roboclaw_driver/roboclaw_driver.py", line 700, in ForwardM1
    return _write1(address, Cmd.M1FORWARD, val)
  File "/home/nano/catkin_ws/src/roboclaw_ros/roboclaw_node/src/roboclaw_driver/roboclaw_driver.py", line 335, in _write1
    _sendcommand(address, cmd)
  File "/home/nano/catkin_ws/src/roboclaw_ros/roboclaw_node/src/roboclaw_driver/roboclaw_driver.py", line 126, in _sendcommand
    port.write(chr(address))
**NameError: global name 'port' is not defined**
[WARN] [1592845100.646772]: Problem getting roboclaw version
Traceback (most recent call last):
  File "/home/nano/catkin_ws/src/roboclaw_ros/roboclaw_node/nodes/roboclaw_pyscript.py", line 332, in <module>
    node = Node()
  File "/home/nano/catkin_ws/src/roboclaw_ros/roboclaw_node/nodes/roboclaw_pyscript.py", line 174, in __init__
    if not version[0]:
**UnboundLocalError: local variable 'version' referenced before assignment**
[roboclaw_node-8] process has died [pid 8459, exit code 1, cmd /home/nano/catkin_ws/src/roboclaw_ros/roboclaw_node/nodes/roboclaw_pyscript.py __name:=roboclaw_node __log:=/home/nano/.ros/log/8e2cd43a-b4a9-11ea-93ad-00044be65023/roboclaw_node-8.log].
log file: /home/nano/.ros/log/8e2cd43a-b4a9-11ea-93ad-00044be65023/roboclaw_node-8*.log

I am able to see the driver when I type the command usb-devices into my terminal window. 
![usb_devices](https://user-images.githubusercontent.com/55637425/85620754-3a3e4180-b632-11ea-8cc7-d1bbd9d375a4.JPG)

> 

Any input would be helpful in debugging this issue.

**Comment by DariusStu** [comment]
I ran project with root level privileges (sudo), and everything is working. The issue was ROS didn't have access rights to some usb ports.
